services:
  - docker
language: node_js
node_js:
  - "10"
env:
  global:
    - REPO=${TRAVIS_REPO_SLUG,,}
    - IMAGE=$REPO:${TRAVIS_COMMIT:0:8}
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_fbd669cc7dcd_key -iv $encrypted_fbd669cc7dcd_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - curl -sSL https://sdk.cloud.google.com | CLOUDSDK_CORE_DISABLE_PROMPTS=1 bash >/dev/null
  - export PATH=/home/travis/google-cloud-sdk/bin:$PATH
install:
  - gcloud components install kubectl --quiet
script: true
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch:
      - dev
      - stage
      - master
