FROM node:10.15.0

ENV NODE_ENV production
ENV HOST 0.0.0.0
ENV PORT 3000
ENV SERVICE_NAME m2-products-api
ENV JWT_SECRET ''
ENV MEDIA_URL ''
ENV MAGENTO_API_URL ''
ENV MAGENTO_ACCESS_TOKEN ''
ENV ATTRIBUTE_SETS ''
ENV PRODUCTS_PAGE_SIZE 40
ENV REDIS_HOST ''
ENV REDIS_KEY_PREFIX 'm2-api:'
ENV CACHE true
ENV SLACK_WEBHOOK_URL ''
ENV SLACK_CHANNEL ''

WORKDIR /app
COPY . /app

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
