apiVersion: v1
kind: Secret
metadata:
  name: yarn-m2-products-api
type: Opaque
data:
  NODE_ENV : c3RhZ2luZwo=
  PORT : MzAwMAo=
  SERVICE_NAME : bTItcHJvZHVjdHMtYXBpCg==
  JWT_SECRET: c2FOdGFQYWlSYjl3S25KcDJXOFBkRAo=
  CRYPTO_SECRET: cU5ydlhINFVKdXc3MlhETHJrU3F6Rgo=
  MEDIA_URL : aHR0cHM6Ly9zdGFnZS1ob2Z5LmtpZGwubm8vbWVkaWEvY2F0YWxvZy9wcm9kdWN0Cg==
  MAGENTO_API_URL : bWFnZW50bwo=
  MAGENTO_ACCESS_TOKEN : NnYweWRzdHN4a21ya2g1bzEzdGM4YmdsMHhmZXVpcjkK
  ATTRIBUTE_SETS : J3sieWFybiI6MTYsICJuZWVkbGVzIjoxN30nCg==
  PRODUCTS_PAGE_SIZE : NDAK
  REDIS_HOST : eWFybi1wYXR0ZXJuLXJlZGlzCg==
  REDIS_KEY_PREFIX : bTItYXBpOgo=
  CACHE : dHJ1ZQo=
  SLACK_WEBHOOK_URL: J2h0dHBzOi8vaG9va3Muc2xhY2suY29tL3NlcnZpY2VzL1Q0NVFXVTZNVS9CSjFGOThHNk0vMWw4V2oxRWFnZUZDaDN6VEtPUWJRbldBJwo=
  SLACK_CHANNEL: J2hveV9zeXN0ZW1fYm90Jwo=
