apiVersion: v1
kind: Secret
metadata:
  name: yarn-jwt-auth
type: Opaque
data:
  NODE_ENV:
  PORT:
  SERVICE_NAME:
  JWT_SECRET:
  MEDIA_URL:
  MAGENTO_API_URL:
  MAGENTO_ACCESS_TOKEN:
  ATTRIBUTE_SETS:
  PRODUCTS_PAGE_SIZE:
  REDIS_HOST:
  REDIS_KEY_PREFIX:
  CACHE:
  SLACK_WEBHOOK_URL:
  SLACK_CHANNEL:
