apiVersion: v1
kind: Secret
metadata:
  name: yarn-m2-products-api
type: Opaque
data:
  NODE_ENV : c3RhZ2luZw==
  PORT : MzAwMA==
  SERVICE_NAME : bTItcHJvZHVjdHMtYXBp
  JWT_SECRET : c2FOdGFQYWlSYjl3S25KcDJXOFBkRA==
  CRYPTO_SECRET : cU5ydlhINFVKdXc3MlhETHJrU3F6Rg==
  MEDIA_URL : aHR0cHM6Ly9zdGFnZS1ob2Z5LmtpZGwubm8vbWVkaWEvY2F0YWxvZy9wcm9kdWN0
  MAGENTO_API_URL : IGh0dHBzOi8vc3RhZ2UtaG9meS5raWRsLm5v
  MAGENTO_ACCESS_TOKEN : NnYweWRzdHN4a21ya2g1bzEzdGM4YmdsMHhmZXVpcjk=
  ATTRIBUTE_SETS : eWFybjoxNixuZWVkbGVzOjE3
  PRODUCTS_PAGE_SIZE : NDA=
  REDIS_HOST : eWFybi1wYXR0ZXJuLXJlZGlz
  REDIS_KEY_PREFIX : bTItYXBpOg==
  CACHE : dHJ1ZQ==
  SLACK_WEBHOOK_URL : aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDQ1UVdVNk1VL0JKMUY5OEc2TS8xbDhXajFFYWdlRkNoM3pUS09RYlFuV0E=
  SLACK_CHANNEL : aG95X3N5c3RlbV9ib3Q=
  LOGGER: dHJ1ZQ==
  GA_TRACKING_ID: VUEtMTA3NTcxNzA3LTQ=
