
name: Deploy Hofy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/yarn-m2-api-fastify
          git stash
          git pull -f origin master
          echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
          yarn install --production
          yarn doc
          pm2 reload hoy-b2c:hofy-m2-api
          pm2 save
